### ISSUE TITLE
More explicit log and progress bar in ModelEvaluation.compare_models

### ISSUE THREAD

**Issue by MischaPanch** [aai-institute/sensAI#77]
There might be other places that could use a progress bar and logs, feel free to extend the issue

I think it would be nice to use tqdm for that, does anything speak against it?

**Comment by opcode81** [comment]
`compare_models` logs quite a lot already. What were you missing?

The trouble is that progress bars interfere with logs because they assume that they are the only ones writing to stdout, and if you mix them, you get garbled output. Since the progress is already discernable in the logs, I don't think we actually need progress bars.
