### ISSUE TITLE
Add InMemoryPersistentKeyValueCache

### ISSUE THREAD

**Issue by MischaPanch** [aai-institute/sensAI#81]
I was surprised not to find this (although in-memory is kinda colliding with "Persistent").

It's going to very useful for me since I'll be reusing cached ColumnGenerators across multiple VectorModels, so an in-memory cache is appropriate.

Do you agree that this would be a useful extension? @opcode81

**Comment by opcode81** [comment]
I agree. To deal with the naming issue, we should add `KeyValueCache`, which shall be what `PersistentKeyValueCache` is now, and `PersistentKeyValueCache` can just inherit from it with `pass` for now; maybe we'll find useful stuff to add to it later.

The new cache can then be `InMemoryKeyValueCache(KeyValueCache)`.

We'll also want to change some interfaces to use `KeyValueCache` rather than `PersistentCacheValueCache`. Maybe it's easiest to start with a rename of `PersistentKeyValueCache`, as this will update all references, and then reintroduce it only in module `cache`.

**Comment by MischaPanch** [comment]
Cool, I'll make a PR
